---
title: "PredicTR replicate"
output: html_document
date: "2025-03-18"
---

## Install/load packages and import data

```{r setup, include=FALSE}
library(survival)
library(survcomp)
library(MASS)
library(rms)
library(polspline)
library(knitr)
library(readxl)
if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(survival,
               Hmisc,
               pec,
               timeROC,
               riskRegression,
               rms,
               knitr,
               kableExtra,
               tidyverse)

options(show.signif.stars = FALSE)  # display statistical intelligence

#Load data

data <- read_excel("~/Downloads/Lauren/Med school/Research/PredicTR/Predictor cleaned dataset ( recieved Syed Haider 2.3.17 merged_data) +Manchester gender info.xls")

str(data)
training <-  data[data$set == "Training", ]
val <- data[data$set == "Validation", ]

all_vars <- c("BCL2", "COX2", "CyclinD1", "EGFRext", "HIF1alpha", "PLK1","Survivin", 
              "p16", "HPVISHHR","TILS", "Gender","Age at Diagnosis", "Surgery", 
              "RT", "CT", "T", "N", "Smoking status")
cont_vars <- c("BCL2", "COX2", "CyclinD1", "EGFRext", "HIF1alpha", "PLK1","Survivin")

biomarkers <- c("BCL2", "COX2", "CyclinD1", "EGFRext", "HPVISHHR", "p16", "PLK1", "Survivin","TILS")

#Set which vars to select and keep them
predictr_data <- subset(data, select = c(all_vars, "t.os", "Outcome"))

to_numeric <- function(data, vars) {
  for (col in vars) {
    if (col!="Gender"){
      if (is.factor(data[[col]]) || is.character(data[[col]])) {
            data[[col]] <- as.character(data[[col]])
            data[[col]][data[[col]] == "NA"] <- NA
            data[[col]] <- as.numeric(data[[col]])
          }
    }
      # Handle NAs, numeric conversion except gender.
    
  }

#  #scale the continuous vars, "cont_vars" then z-transform
#  for (col in cont_vars) {
#    data[[col]] <- as.numeric(as.character(data[[col]]))
#    data[[col]] <- scale(data[[col]]/30)[,1]
# }
 
  # Dichotomise p16
#  data$p16 <- as.numeric(as.character(data$p16))
#  data$p16 <- factor(ifelse(data$p16 >= 140, 1, 0))


  return(data)
} 



#Convert everything except Gender to numeric
predictr_data <- to_numeric(predictr_data, )
#str(predictr_data)

# Convert "NA" to NA in Gender:
predictr_data$Gender[predictr_data$Gender == "NA"] <- NA

#Remove NAs (based on which variables?)
complete_data0 <- predictr_data[complete.cases(predictr_data), ]
#Gives 471 observations
complete_data1 <- predictr_data[!is.na(predictr_data$t.os), ]
# Gives 835 observations
complete_data2 <- predictr_data[!is.na(predictr_data$t.os) & !is.na(predictr_data$Outcome), ]
# Gives 809 observations

#Convert continuous variables to z scores, factor p16, HR-HPV DNA, TILs, age, gender, T-category, N-category, smoking status, surgery, RT, CT (using lowest category as baseline group). Need to make sure everything is already numeric
preprocess <- function(data, cont_vars) {
#scale the continuous vars, "cont_vars" then z-transform
  for (col in cont_vars) {
    data[[col]] <- as.numeric(as.character(data[[col]]))
    data[[col]] <- scale(data[[col]]/30)[,1]
 }
 
  # Dichotomise p16
  data$p16_binary <- factor(ifelse(data$p16 >= 140, 1, 0))
  # Dichotomise age
  data$`Age at Diagnosis` <- factor(ifelse(data$`Age at Diagnosis`>= 50, 1, 0))
  # Factor variables:
  data$HPVISHHR <- factor(data$HPVISHHR)
  data$TILS <- factor(data$TILS)
  data$T <- factor(data$T)
  data$N <- factor(data$N)
  data$`Smoking status` <- factor(data$`Smoking status`)
  data$Surgery <- factor(data$Surgery)
  data$RT <- factor(data$RT)
  data$CT <- factor(data$CT)
  data$Gender <- factor(data$Gender)

  return(data)
} 

data_processed <- preprocess(complete_data1, cont_vars)

str(data_processed)
#Split into training and validation cohorts
training_data <- predictr_data[data$set == "Training", ]
val_data <-predictr_data[data$set == "Validation", ]

#Remove NAs, convert all vars to numeric except Gender
training_ptd <- preprocess_data(training_data, c("t.os", "Outcome", all_vars))
#Get 259 
training_ptd2 <- preprocess_data(training_data, c("t.os", all_vars))
#Get 263 => must be 4 observations where "Outcome" is unknown but "t.os" is known

str(training_ptd2)
unique(complete_data1$T)

```

```{r}




```

## Table S4

```{r}
summary(predictr_data[biomarkers])
```
## Table S5
n are different - many more observations than in supplemental materials.
```{r}

# Function for univariable Cox
univariable_cox <- function(data, vars) {
  results <- lapply(vars, function(var) {
    
    # Subset to non-NA for this variable, t.os, and Outcome
    valid_data <- data[!is.na(data[[var]]) & !is.na(data$t.os) & !is.na(data$Outcome), ]
    n_obs <- nrow(valid_data)
    
    formula <- as.formula(paste("Surv(t.os, Outcome) ~", var))
    model <- coxph(formula, data = data)
    coef_summary <- summary(model)$coefficients
    return(data.frame(Variable = var, 
                      Coefficient = coef_summary[, "coef"],
                      Lower = coef_summary[, "coef"] - 1.96 * coef_summary[, "se(coef)"],
                      Upper = coef_summary[, "coef"] + 1.96 * coef_summary[, "se(coef)"],
                      P = coef_summary[, "Pr(>|z|)"],
                      n = n_obs))
  })
  results_df <- bind_rows(results)
  # Adjust p-values using Benjamini & Hochberg method
  results_df$Q <- p.adjust(results_df$P, method = "BH")
  return(bind_rows(results_df))
}

colnames(data_processed)[colnames(data_processed) == 'Age at Diagnosis'] <- 'Age.at.Diagnosis'
colnames(data_processed)[colnames(data_processed) == 'Smoking status'] <- 'Smoking.status'

all_vars1 <- c("BCL2", "COX2", "CyclinD1", "EGFRext", "HIF1alpha", "PLK1","Survivin", 
              "p16_binary", "HPVISHHR","TILS", "Gender","Age.at.Diagnosis", "Surgery", 
              "RT", "CT", "T", "N", "Smoking.status")

print(univariable_cox(data_processed, all_vars1))

data_processed

```
